# This is a basic workflow to help you get started with Actions

name: Meu primeiro CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
ci:
runs-on: ubuntu-latest
steps:
- name: build
run: |
echo iniciando Build...
echo Branch utilizada ${{github.ref.name}}, Evento ${{github.event_name}}
