# This is a basic workflow to help you get started with Actions

name: Meu primeiro CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
compile:
runs-on: ubuntu-latest
steps:
- name: Build
run: |
echo iniciando Build...
echo Branch utilizada ${{ github.ref.name }}, Evento ${{ github.event_name }]

test:
needs: compile
ruins-on: ubuntu-latest
steps: 
- name: Test
run: echo Iniciando Test...

build:
needs: test
runs-on: ubuntu-latest
steps:
- name: Build
run: |
echo Branch utilizada ${{ github.ref.name }}, Evento ${{ github.event_name }}
